version: '3.6'

volumes:
  dbdata:
  esdata:

services:
  db:
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sylius-formation
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '3307:3306'

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'

