sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

app_supplier:
    resource: |
        alias: app.supplier
        except: ['show']
        section: admin
        templates: "@SyliusAdmin\\Crud"
        grid: app_admin_supplier
    type: sylius.resource
    prefix: /admin
    
app_traveller:
    resource: |
        alias: app.videogame
        except: ['show']
        section: admin
        templates: "@SyliusAdmin\\Crud"
        grid: app_admin_videogame
    type: sylius.resource
    prefix: /admin

sylius_paypal_admin:
    resource: "@SyliusPayPalPlugin/Resources/config/admin_routing.yml"
    prefix: /admin 
    
app_admin_supplier_trust:
    path : /admin/suppliers/{id}/trust
    methods: [PUT]
    defaults:
        _controller: app.controller.supplier:applyStateMachineTransitionAction
        _sylius:
            state_machine:
                graph: app_supplier
                transition: trust
            redirect: referer
            flash: app.ui.supplier_trusted
            
                


